# test/sanpshot.py
"""Auto-generated expected snapshots - generated from a verified-correct parser run.
Regenerate ONLY after manually confirming a change is correct, via generate_snapshots.py.
"""

SNAPSHOTS = {'javascript': {'classes': {'Base': {'base_classes': [],
                                     'class_variables': [],
                                     'decorators': [],
                                     'docstring': None,
                                     'methods': {},
                                     'name': 'Base'},
                            'MyClass': {'base_classes': ['Base'],
                                        'class_variables': [],
                                        'decorators': [],
                                        'docstring': None,
                                        'methods': {'_privateMethod': {'decorators': [],
                                                                       'docstring': None,
                                                                       'is_async': False,
                                                                       'is_private': True,
                                                                       'name': '_privateMethod',
                                                                       'params': [],
                                                                       'returns': None},
                                                    'arrowProp': {'decorators': [],
                                                                  'docstring': 'Arrow property doc',
                                                                  'is_async': True,
                                                                  'is_private': False,
                                                                  'name': 'arrowProp',
                                                                  'params': [],
                                                                  'returns': None},
                                                    'asyncMethod': {'decorators': [],
                                                                    'docstring': 'Async method doc',
                                                                    'is_async': True,
                                                                    'is_private': False,
                                                                    'name': 'asyncMethod',
                                                                    'params': [{'default_value': None,
                                                                                'name': 'data',
                                                                                'type_hint': None}],
                                                                    'returns': None},
                                                    'myMethod': {'decorators': [],
                                                                 'docstring': 'Method doc',
                                                                 'is_async': False,
                                                                 'is_private': False,
                                                                 'name': 'myMethod',
                                                                 'params': [{'default_value': None,
                                                                             'name': 'x',
                                                                             'type_hint': None}],
                                                                 'returns': None}},
                                        'name': 'MyClass'},
                            'NoDocClass': {'base_classes': ['Base'],
                                           'class_variables': [],
                                           'decorators': [],
                                           'docstring': None,
                                           'methods': {'methodNoDoc': {'decorators': [],
                                                                       'docstring': None,
                                                                       'is_async': False,
                                                                       'is_private': False,
                                                                       'name': 'methodNoDoc',
                                                                       'params': [],
                                                                       'returns': None}},
                                           'name': 'NoDocClass'}},
                'functions': {'_privateTopFunc': {'decorators': [],
                                                  'docstring': None,
                                                  'is_async': False,
                                                  'is_private': True,
                                                  'name': '_privateTopFunc',
                                                  'params': [],
                                                  'returns': None},
                              'topArrow': {'decorators': [],
                                           'docstring': None,
                                           'is_async': False,
                                           'is_private': False,
                                           'name': 'topArrow',
                                           'params': [{'default_value': None,
                                                       'name': 'a',
                                                       'type_hint': None},
                                                      {'default_value': None,
                                                       'name': 'b',
                                                       'type_hint': None}],
                                           'returns': None},
                              'topAsyncArrow': {'decorators': [],
                                                'docstring': None,
                                                'is_async': True,
                                                'is_private': False,
                                                'name': 'topAsyncArrow',
                                                'params': [{'default_value': None,
                                                            'name': 'x',
                                                            'type_hint': None}],
                                                'returns': None},
                              'topFunc': {'decorators': [],
                                          'docstring': None,
                                          'is_async': False,
                                          'is_private': False,
                                          'name': 'topFunc',
                                          'params': [{'default_value': None,
                                                      'name': 'x',
                                                      'type_hint': None}],
                                          'returns': None}},
                'global_variables': [],
                'has_entry_point': True,
                'imports': [{'alias': None, 'is_from_import': True, 'module': 'fs', 'names': []},
                            {'alias': None,
                             'is_from_import': False,
                             'module': 'path',
                             'names': []}],
                'module_docstring': None},
 'python': {'classes': {'Base': {'base_classes': [],
                                 'class_variables': [],
                                 'decorators': [],
                                 'docstring': 'Base class docstring',
                                 'methods': {},
                                 'name': 'Base'},
                        'MyClass': {'base_classes': ['Base'],
                                    'class_variables': [],
                                    'decorators': [],
                                    'docstring': 'MyClass docstring',
                                    'methods': {'_private_method': {'decorators': [],
                                                                    'docstring': None,
                                                                    'is_async': False,
                                                                    'is_private': True,
                                                                    'name': '_private_method',
                                                                    'params': [{'default_value': None,
                                                                                'name': 'self',
                                                                                'type_hint': None}],
                                                                    'returns': None},
                                                'async_method': {'decorators': [],
                                                                 'docstring': 'Async method '
                                                                              'docstring',
                                                                 'is_async': True,
                                                                 'is_private': False,
                                                                 'name': 'async_method',
                                                                 'params': [{'default_value': None,
                                                                             'name': 'self',
                                                                             'type_hint': None},
                                                                            {'default_value': None,
                                                                             'name': 'data',
                                                                             'type_hint': None}],
                                                                 'returns': None},
                                                'method': {'decorators': [],
                                                           'docstring': 'Method docstring',
                                                           'is_async': False,
                                                           'is_private': False,
                                                           'name': 'method',
                                                           'params': [{'default_value': None,
                                                                       'name': 'self',
                                                                       'type_hint': None},
                                                                      {'default_value': None,
                                                                       'name': 'x',
                                                                       'type_hint': None},
                                                                      {'default_value': '2',
                                                                       'name': 'y',
                                                                       'type_hint': None}],
                                                           'returns': None},
                                                'static_method': {'decorators': ['staticmethod'],
                                                                  'docstring': None,
                                                                  'is_async': False,
                                                                  'is_private': False,
                                                                  'name': 'static_method',
                                                                  'params': [{'default_value': None,
                                                                              'name': 'a',
                                                                              'type_hint': None},
                                                                             {'default_value': None,
                                                                              'name': 'b',
                                                                              'type_hint': None}],
                                                                  'returns': None}},
                                    'name': 'MyClass'},
                        'NoDocClass': {'base_classes': ['Base'],
                                       'class_variables': [],
                                       'decorators': [],
                                       'docstring': None,
                                       'methods': {'method_no_doc': {'decorators': [],
                                                                     'docstring': None,
                                                                     'is_async': False,
                                                                     'is_private': False,
                                                                     'name': 'method_no_doc',
                                                                     'params': [{'default_value': None,
                                                                                 'name': 'self',
                                                                                 'type_hint': None}],
                                                                     'returns': None}},
                                       'name': 'NoDocClass'}},
            'functions': {'_private_top_function': {'decorators': [],
                                                    'docstring': None,
                                                    'is_async': False,
                                                    'is_private': True,
                                                    'name': '_private_top_function',
                                                    'params': [],
                                                    'returns': None},
                          'top_async_function': {'decorators': [],
                                                 'docstring': None,
                                                 'is_async': True,
                                                 'is_private': False,
                                                 'name': 'top_async_function',
                                                 'params': [{'default_value': None,
                                                             'name': 'x',
                                                             'type_hint': None}],
                                                 'returns': None},
                          'top_function': {'decorators': [],
                                           'docstring': 'Top function docstring',
                                           'is_async': False,
                                           'is_private': False,
                                           'name': 'top_function',
                                           'params': [{'default_value': None,
                                                       'name': 'a',
                                                       'type_hint': None},
                                                      {'default_value': '2',
                                                       'name': 'b',
                                                       'type_hint': None},
                                                      {'default_value': None,
                                                       'name': '*args',
                                                       'type_hint': None},
                                                      {'default_value': None,
                                                       'name': '**kwargs',
                                                       'type_hint': None}],
                                           'returns': None}},
            'global_variables': [],
            'has_entry_point': True,
            'imports': [{'alias': None, 'is_from_import': False, 'module': 'os', 'names': []},
                        {'alias': None,
                         'is_from_import': True,
                         'module': 'pathlib',
                         'names': ['Path']},
                        {'alias': None,
                         'is_from_import': True,
                         'module': 'utils',
                         'names': ['another_helper', 'helper']}],
            'module_docstring': 'Sample Python module for parser snapshot test.'},
 'typescript': {'classes': {'Base': {'base_classes': [],
                                     'class_variables': [],
                                     'decorators': [],
                                     'docstring': None,
                                     'methods': {},
                                     'name': 'Base'},
                            'MyClass': {'base_classes': ['Base'],
                                        'class_variables': [],
                                        'decorators': [],
                                        'docstring': None,
                                        'methods': {'_privateMethod': {'decorators': [],
                                                                       'docstring': None,
                                                                       'is_async': False,
                                                                       'is_private': True,
                                                                       'name': '_privateMethod',
                                                                       'params': [],
                                                                       'returns': None},
                                                    'arrowProp': {'decorators': [],
                                                                  'docstring': 'Arrow property doc',
                                                                  'is_async': True,
                                                                  'is_private': False,
                                                                  'name': 'arrowProp',
                                                                  'params': [],
                                                                  'returns': None},
                                                    'asyncMethod': {'decorators': [],
                                                                    'docstring': 'Async method doc',
                                                                    'is_async': True,
                                                                    'is_private': False,
                                                                    'name': 'asyncMethod',
                                                                    'params': [{'default_value': None,
                                                                                'name': 'data',
                                                                                'type_hint': 'string'}],
                                                                    'returns': None},
                                                    'myMethod': {'decorators': [],
                                                                 'docstring': 'Method doc',
                                                                 'is_async': False,
                                                                 'is_private': False,
                                                                 'name': 'myMethod',
                                                                 'params': [{'default_value': None,
                                                                             'name': 'x',
                                                                             'type_hint': 'number'}],
                                                                 'returns': None}},
                                        'name': 'MyClass'},
                            'NoDocClass': {'base_classes': ['Base'],
                                           'class_variables': [],
                                           'decorators': [],
                                           'docstring': None,
                                           'methods': {'methodNoDoc': {'decorators': [],
                                                                       'docstring': None,
                                                                       'is_async': False,
                                                                       'is_private': False,
                                                                       'name': 'methodNoDoc',
                                                                       'params': [],
                                                                       'returns': None}},
                                           'name': 'NoDocClass'}},
                'functions': {'greet': {'decorators': [],
                                        'docstring': None,
                                        'is_async': False,
                                        'is_private': False,
                                        'name': 'greet',
                                        'params': [{'default_value': None,
                                                    'name': 'name',
                                                    'type_hint': 'string'},
                                                   {'default_value': None,
                                                    'name': 'title',
                                                    'type_hint': 'string'},
                                                   {'default_value': "'!'",
                                                    'name': 'punctuation',
                                                    'type_hint': 'string'}],
                                        'returns': None},
                              'topArrow': {'decorators': [],
                                           'docstring': None,
                                           'is_async': False,
                                           'is_private': False,
                                           'name': 'topArrow',
                                           'params': [{'default_value': None,
                                                       'name': 'a',
                                                       'type_hint': 'number'},
                                                      {'default_value': None,
                                                       'name': 'b',
                                                       'type_hint': 'number'}],
                                           'returns': None},
                              'topAsyncArrow': {'decorators': [],
                                                'docstring': None,
                                                'is_async': True,
                                                'is_private': False,
                                                'name': 'topAsyncArrow',
                                                'params': [{'default_value': None,
                                                            'name': 'x',
                                                            'type_hint': 'number'}],
                                                'returns': None},
                              'topFunc': {'decorators': [],
                                          'docstring': None,
                                          'is_async': False,
                                          'is_private': False,
                                          'name': 'topFunc',
                                          'params': [{'default_value': None,
                                                      'name': 'x',
                                                      'type_hint': 'number'}],
                                          'returns': None}},
                'global_variables': [],
                'has_entry_point': True,
                'imports': [{'alias': None, 'is_from_import': True, 'module': 'fs', 'names': []},
                            {'alias': None,
                             'is_from_import': False,
                             'module': 'path',
                             'names': []}],
                'module_docstring': None}}