# generator.py
"""This module generates markdown documentation from analysis results."""
from typing import List
from pathlib import Path
from models import ProjectAnalysis, ModuleSummary

class DocumentationGenerator:
    def __init__(self, output_dir: str = "output"):
        """
        Initialize the documentation generator.
        
        Args:
            output_dir: Directory to save generated documentation
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate_readme(self, project_analysis: ProjectAnalysis, project_name: str) -> str:
        """
        Generate README.md (overview documentation).
        
        Args:
            project_analysis: High-level project analysis
            project_name: Name of the project
            
        Returns:
            Path to generated README.md
        """
        readme_path = self.output_dir / "README.md"
        content = f"""# {project_name}
## Overview

{project_analysis.project_purpose}

## Architecture

{project_analysis.architecture_overview}

## Entry Points

The following files can be run directly:

"""

        for entry_point in project_analysis.entry_points:
            content += f"- `{entry_point}`\n"
        
        content += f"""

## Module Relationships

{project_analysis.module_relationships}

## Design Patterns

"""
        
        if project_analysis.design_patterns:
            for pattern in project_analysis.design_patterns:
                content += f"- {pattern}\n"
        else:
            content += "No specific design patterns identified.\n"
        
        content += """

## Getting Started

[Add setup instructions here]

## Usage

[Add usage examples here]

---

*This documentation was automatically generated by the Code Documentation Agent.*
"""
        
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(readme_path)

    def generate_technical_doc(
        self, 
        project_analysis: ProjectAnalysis, 
        module_summaries: List[ModuleSummary],
        project_name: str
    ) -> str:
        """
        Generate TECHNICAL_DOC.md (detailed technical documentation).
        
        Args:
            project_analysis: High-level project analysis
            module_summaries: List of all module summaries
            project_name: Name of the project
            
        Returns:
            Path to generated TECHNICAL_DOC.md
        """
        tech_doc_path = self.output_dir / "TECHNICAL_DOC.md"
        
        content = f"""# {project_name} - Technical Documentation

## Architecture Overview

{project_analysis.architecture_overview}

## Module Relationships

{project_analysis.module_relationships}

## Design Patterns

"""
        
        if project_analysis.design_patterns:
            for pattern in project_analysis.design_patterns:
                content += f"- **{pattern}**: [Description of how it's used]\n"
        else:
            content += "No specific design patterns identified.\n"
        
        content += """

---

## Module Reference

"""
        
        # Sort modules by path for consistent ordering
        sorted_summaries = sorted(module_summaries, key=lambda x: x.file_path)
        
        for summary in sorted_summaries:
            content += f"""
### `{summary.file_path}`

**Purpose:** {summary.purpose}

**Responsibilities:**
"""
            for resp in summary.responsibilities:
                content += f"- {resp}\n"
            
            content += f"""
**Key Components:**
"""
            for comp in summary.key_components:
                content += f"- `{comp}`\n"
            
            if summary.dependencies:
                content += f"""
**Dependencies:**
"""
                for dep in summary.dependencies:
                    content += f"- `{dep}`\n"
            
            content += "\n---\n"
        
        content += """

## Development Guidelines

[Add coding standards, contribution guidelines, etc.]

## Testing

[Add testing instructions]

---

*This technical documentation was automatically generated by the Code Documentation Agent.*
"""
        
        with open(tech_doc_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(tech_doc_path)
    
    def generate_all(
        self, 
        project_analysis: ProjectAnalysis, 
        module_summaries: List[ModuleSummary],
        project_name: str
    ) -> dict:
        """
        Generate all documentation files.
        
        Args:
            project_analysis: High-level project analysis
            module_summaries: List of all module summaries
            project_name: Name of the project
            
        Returns:
            Dictionary with paths to generated files
        """
        readme_path = self.generate_readme(project_analysis, project_name)
        tech_doc_path = self.generate_technical_doc(project_analysis, module_summaries, project_name)
        
        return {
            "readme": readme_path,
            "technical_doc": tech_doc_path
        } 